- name: Update apt packages
  apt:
    force_apt_get: yes
    autoclean: yes
    autoremove: yes
    update_cache: yes
    upgrade: dist
    cache_valid_time: 432000

- name: Check if reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot
  reboot:
  when: reboot_required.stat.exists
