static_dns: "1.1.1.1"
pihole_image: "pihole/pihole:latest"
pihole_ftl_max_db_days: "180"
pihole_webpassword: Intranet # example value, change it and better use ansible-vault

#Here I'm pointing to my local unbound dns server, otherwise you can point to a remote dns server as commented out
#pihole_dns: "1.1.1.1;2606:4700:4700::1111"
pihole_dns: "127.0.0.1#5335"

pihole_rev_server: "true"
pihole_rev_server_domain: "Homehub3"
pihole_rev_server_target: "192.168.0.1"
pihole_rev_server_cidr: "192.168.0.1/24"
pihole_ha_mode: yes
pihole_vip_ipv4: "192.168.0.1/24"
pihole_vip_ipv6: "fd00::1/64"
pihole_dhcp_active: "true"
pihole_dhcp_start: "192.168.0.21"
pihole_dhcp_end: "192.168.0.255"
pihole_dhcp_router: "192.168.0.5"
sync_target: "{{ pihole_vip_ipv4.split('/')[0] }}"
